[package]
name = "day12"
version = "0.1.0"
authors = ["Bluesy1 <68259537+Bluesy1@users.noreply.github.com>"]
edition = "2021"

[lib]
path = "src/main.rs"

[dependencies]
cached = "0.46.1"

# [dependencies]
# aho-corasick = "1.1.2"
# regex = "1.10.2"
